server:
  port: 8080
  servlet:
    context-path: /platform
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB       # 上传文件总的最大值
      max-request-size: 10MB    # 单个文件的最大值
# Dubbo
dubbo:
  application:
    name: platform # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  consumer:
    check: false
    timeout: 120000